### ISSUE TITLE
Failed provision will automatically cause many deprovision temporary projects generated

### ISSUE THREAD

**Issue by qwang1** [kubevirt/kubevirt-ansible#281] opened 2018-06-12 09:04 UTC
Hi there,

Once an APB provision failed, the deprovision process will continuously generate many temporary projects like this:

```
[root@cnv-executor-qwang-apb-11-master1 ~]# oc get namespace
NAME                               STATUS    AGE
app-storage                        Active    1d
default                            Active    1d
dh-import-vm-disk-apb-depr-2g7jm   Active    1m
dh-import-vm-disk-apb-depr-2q76p   Active    3m
dh-import-vm-disk-apb-depr-2sphw   Active    6m
dh-import-vm-disk-apb-depr-44txl   Active    6m
dh-import-vm-disk-apb-depr-5pn6q   Active    2m
dh-import-vm-disk-apb-depr-65hbx   Active    7m
dh-import-vm-disk-apb-depr-75cmt   Active    3m
dh-import-vm-disk-apb-depr-7lh9p   Active    3m
dh-import-vm-disk-apb-depr-7pcnl   Active    32s
dh-import-vm-disk-apb-depr-7r9n2   Active    6m
dh-import-vm-disk-apb-depr-7rd7k   Active    5m
dh-import-vm-disk-apb-depr-9hp4n   Active    4m
dh-import-vm-disk-apb-depr-9tfsg   Active    2m
dh-import-vm-disk-apb-depr-9x69z   Active    4m
dh-import-vm-disk-apb-depr-b2zkt   Active    2m
dh-import-vm-disk-apb-depr-b78nx   Active    7m
dh-import-vm-disk-apb-depr-bkfnq   Active    59s
dh-import-vm-disk-apb-depr-bv78d   Active    2m
dh-import-vm-disk-apb-depr-bvblc   Active    1m
dh-import-vm-disk-apb-depr-c4crt   Active    3m
dh-import-vm-disk-apb-depr-d2hfs   Active    6m
dh-import-vm-disk-apb-depr-d5xlv   Active    7m
dh-import-vm-disk-apb-depr-flps6   Active    7m
dh-import-vm-disk-apb-depr-hqs6f   Active    1m
dh-import-vm-disk-apb-depr-jcvv5   Active    9m
dh-import-vm-disk-apb-depr-khftv   Active    6s
dh-import-vm-disk-apb-depr-kxhct   Active    1m
dh-import-vm-disk-apb-depr-kz7n9   Active    5m
dh-import-vm-disk-apb-depr-lz5vx   Active    5m
dh-import-vm-disk-apb-depr-njgdk   Active    46s
dh-import-vm-disk-apb-depr-phlj6   Active    4m
dh-import-vm-disk-apb-depr-pv6cc   Active    19s
dh-import-vm-disk-apb-depr-pvqwd   Active    4m
dh-import-vm-disk-apb-depr-s7sql   Active    7m
dh-import-vm-disk-apb-depr-z8jwt   Active    2m
dh-import-vm-disk-apb-depr-zjr9v   Active    5m
dh-import-vm-disk-apb-prov-htkpr   Active    10m
dh-virtualization-depr-244ng       Active    49m
dh-virtualization-depr-289s8       Active    53m
dh-virtualization-depr-2lrvt       Active    51m
dh-virtualization-depr-2m2qt       Active    52m
dh-virtualization-depr-2wv7l       Active    48m
dh-virtualization-depr-6bgbf       Active    54m
dh-virtualization-depr-6ccdv       Active    52m
dh-virtualization-depr-6j2cf       Active    58m
dh-virtualization-depr-ctwx7       Active    52m
dh-virtualization-depr-d6qx8       Active    53m
dh-virtualization-depr-g2xxh       Active    50m
dh-virtualization-depr-gm9tc       Active    55m
dh-virtualization-depr-j7kc9       Active    50m
dh-virtualization-depr-khx67       Active    56m
dh-virtualization-depr-mtl6q       Active    58m
dh-virtualization-depr-mz66l       Active    55m
dh-virtualization-depr-n4xvv       Active    57m
dh-virtualization-depr-n845b       Active    59m
dh-virtualization-depr-ntldp       Active    51m
dh-virtualization-depr-nx5mp       Active    49m
dh-virtualization-depr-qfnbz       Active    54m
dh-virtualization-depr-tmgsf       Active    56m
dh-virtualization-depr-xc26t       Active    57m
dh-virtualization-prov-4kmwc       Active    1h
dh-virtualization-prov-9s84h       Active    2h
dh-virtualization-prov-dzfmj       Active    2h
dh-virtualization-prov-ftlwk       Active    1h
dh-virtualization-prov-hf5p9       Active    2h
golden-images                      Active    2h
kube-public                        Active    1d
kube-service-catalog               Active    1d
kube-system                        Active    1d
openshift                          Active    1d
openshift-ansible-service-broker   Active    1d
openshift-infra                    Active    1d
openshift-logging                  Active    1d
openshift-node                     Active    1d
openshift-sdn                      Active    1d
openshift-web-console              Active    1d
qwang-import-vm-disk-1             Active    11m
qwang-import-vm-disk-2             Active    7m
```

**Comment by lukas-bednar** [comment] 2018-06-12 09:50
@rthallisey Do you have any idea what we can do about it ?

**Comment by vatsalparekh** [comment] 2018-06-28 06:19
@sreichar @rthallisey yes this seems similar to https://github.com/ansibleplaybookbundle/import-vm-apb/issues/25
I was seeing the same thing in that issue

**Comment by rthallisey** [comment] 2018-07-02 13:29
I haven't reproduced myself.  What version of the broker is this?

**Comment by qwang1** [comment] 2018-07-03 07:47
@rthallisey Hi, I haven't met this these days. It supposed to occur between OCP v3.10.0-0.63.0_2018-06-06.1 to OCP v3.10.0-0.67.0_2018-06-12.1, and broker should have the same version with OCP. Should we put this issue aside temporarily until it happens again or we help you to reproduce it? 

@vatsalparekh Do you have any supplements?

**Comment by lukas-bednar** [comment] 2018-07-03 08:13
I can confirm this behavior on v3.10.0-0.66.0. This issue happened when:
1) apb provisioning failed -> triggering apb deprovision
2) apb deprovision failed -> triggering another apb deprovision
3) new apb deprovision fails again -> going back to step `2)`

I didn't see this issue for a while, because I didn't see APB provisioning fail ...
I believe that this issue is more related to broker than to kubevirt-ansible,
I don't know what could be done in kubevirt-ansible to prevent that.

**Comment by rthallisey** [comment] 2018-07-03 10:43
@lukas-bednar agreed, this is broker behavior.  @qwang1 Can you port this over to https://github.com/openshift/ansible-service-broker ?  Closing it in this repo.

**Closed by rthallisey** 2018-07-03 10:43 UTC
Labels: bug

**Comment by qwang1** [comment] 2018-07-12 11:09
Track it here: https://github.com/openshift/ansible-service-broker/issues/1010
